server:
  address: ${SERVER_ADDRESS:0.0.0.0}
  port: ${SERVER_PORT:7901}

spring:
  application:
    name: video-chat-backoffice
  rsocket:
    server:
      transport: websocket
      mapping-path: ${BACKOFFICE_RSOCKET_MAPPING_PATH:/rsocket}

management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:health,info}
