server:
  address: 0.0.0.0
  port: 7901

spring:
  application:
    name: video-chat-backoffice
  rsocket:
    server:
      transport: websocket
      mapping-path: /rsocket

management:
  endpoints:
    web:
      exposure:
        include: health,info
